CHG-28 Nextech Payments API - new end point to Create Payment Profile By merchantCustomerId
NextechSystems/payfacapidocspub pull request #42
Opened 2024-01-24 09:57 UTC by dharmendra-nextech

Story link:
https://nextech.atlassian.net/browse/CHG-228

2024-01-24 10:13 UTC, mukeshnextech reviewed
Looking Good

2024-01-24 10:13 UTC, mukeshnextech commented on index.html
Looking good

2024-01-25 11:58 UTC, jonhageman requested changes

2024-01-25 11:58 UTC, jonhageman commented on index.html
> +                        <td>PatientGuid</td>
We should refer to this as "MerchantCustomerId" to be consistent.

2024-01-25 11:58 UTC, jonhageman commented on index.html
> +                        <td>Patients Guid</td>
replace with this: "This is the Guid provided by the Nextech merchant. Sometimes referred to as 'Patient Guid'"

2024-01-25 11:58 UTC, jonhageman commented on index.html
> +                        <td>Id from processor linked to payment method</td>
replace with "Id from processor (Stripe) linked to payment method"

2024-01-25 11:58 UTC, jonhageman commented on index.html
> +                         <td>patientGuid</td>
same as above

2024-01-25 11:58 UTC, jonhageman commented on index.html
> +             <p><code>GET https://payfac.api.nextech.com/api/public/paymentProfiles/byMerchantCustomerId/{patientGuid}</code></p>
this should be {merchantCustomerId}

2024-01-25 13:21 UTC, jonhageman approved these changes

2024-01-25 13:21 UTC, merged